server:
 port: 8080
 servlet:
  context-path: /social

spring:
 datasource:
   url: "jdbc:mysql://localhost:3306/social_media"
   username: root
   password: "Datx30112003@fc"

 jpa:
   hibernate:
    ddl_auto: update
   show-sql: true

jwt:
  signerKey: "c3BlY2lmaWNub2lzZXJ1bGVyY291bnRyYWluY2Fubm90c3VkZGVubHlrbm93bmxlYXY="
  valid-duration: 3600 # second
  refreshable-duration: 36000 # second

